# HW 2 Code Solutions
Author: Apara Venkat

```{r}
source("ctmc_simulator.R")
```


## Question 1(c)

```{r}
R_matrix <- function(params, verbose=F) {
    pi_A <- params[1]
    pi_G <- params[2]
    pi_C <- params[3]
    pi_T <- 1 - params[1] - params[2] - params[3]
    
    alpha <- params[4]
    gamma <- params[5]
    beta <- (1 - alpha * (pi_A + pi_G) - gamma * (pi_C + pi_T)) / 2
    if (verbose) {
        cat(pi_A, pi_G, pi_C, pi_T, alpha, beta, gamma, "\n")
    }
    
    R <- matrix(0, nrow=4, ncol=4)
    R[1, 2] <- alpha * pi_G
    R[1, 3] <- beta * pi_C
    R[1, 4] <- beta * pi_T
    R[2, 1] <- alpha * pi_A
    R[2, 3] <- beta * pi_C
    R[2, 4] <- beta * pi_T
    R[3, 1] <- alpha * pi_A
    R[3, 2] <- alpha * pi_G
    R[3, 4] <- beta * pi_T
    R[4, 1] <- alpha * pi_A
    R[4, 2] <- alpha * pi_G
    R[4, 3] <- beta * pi_C
    diag(R) <- -rowSums(R)
    
    return(R)
}

params <- c(0.25, 0.25, 0.25, 0.6, 0.73)
R <- R_matrix(params)

R
```

```{r}
root_str <- "ATTCTGACTATTCGCGTAATCTAGGTATCGACCTACTGGATCCGTAT"
root_split <- strsplit(root_str, "")[[1]]
root <- c()
for (char in root_split) {
    if (char == "A") {
        state <- 1
    }
    else if (char == "G") {
        state <- 2
    }
    else if (char == "C") {
        state <- 3
    }
    else {
        state <- 4
    }
    root <- c(root, state)
}

N <- length(root)
print(root)
print(N)
```

```{r}
set.seed(0)

print(root)

# Evolve until time 1
time_1 <- c()
for (dna in root) {
    sim_res <- simulate_ctmc(dna, R, 1)
    Xt <- sim_res$states
    new_dna <- Xt[length(Xt)]
    time_1 <- c(time_1, new_dna)
}
print(time_1)

# Evolve until time 0.65
time_2 <- c()
for (dna in root) {
    sim_res <- simulate_ctmc(dna, R, 0.65)
    Xt <- sim_res$states
    new_dna <- Xt[length(Xt)]
    time_2 <- c(time_2, new_dna)
}
print(time_2)

# Evolve from t = 0.65 to t = 0.35
time_3 <- c()
for (dna in time_2) {
    sim_res <- simulate_ctmc(dna, R, 0.35)
    Xt <- sim_res$states
    new_dna <- Xt[length(Xt)]
    time_3 <- c(time_3, new_dna)
}
print(time_3)

# Evolve from t = 0.65 to t = 0.3
time_4 <- c()
for (dna in time_2) {
    sim_res <- simulate_ctmc(dna, R, 0.30)
    Xt <- sim_res$states
    new_dna <- Xt[length(Xt)]
    time_4 <- c(time_4, new_dna)
}
print(time_4)


table(c(time_1, time_2, time_3, time_4)) / (4*length(root))
```

```{r}
log_lik <- function(params, data0, t1, data1, t2, data2, t3, data3, t4, data4) {
    
    pi_T <- 1 - params[1] - params[2] - params[3]
    beta <- (1 - params[4] * (params[1] + params[2]) - params[5] * (params[3] + pi_T)) / 2
    params <- c(params, pi_T, beta)
    if (any(params < 0) || any(params > 1)) {
        return(-Inf)
    }
    
    N <- length(data0)
    k <- 20
    R <- R_matrix(params)
    P1 <- estimate_transition_matrix(R, t1, k)
    P2 <- estimate_transition_matrix(R, t2, k)
    P3 <- estimate_transition_matrix(R, t3, k)
    P4 <- estimate_transition_matrix(R, t4, k)
    
    l <- 0
    for (i in seq_len(N)) {
        Xi_0 <- data0[i]
        Xi_1 <- data1[i]
        Xi_2 <- data2[i]
        Xi_3 <- data3[i]
        Xi_4 <- data4[i]
        
        l <- l + log(P1[Xi_0, Xi_1]) + log(P2[Xi_0, Xi_2])
        l <- l + log(P3[Xi_2, Xi_3]) + log(P4[Xi_2, Xi_4])
    }
    
    return(-l)
}

res <- optim(params, log_lik, gr=NULL, root, 1, time_1, 0.65, time_2, 0.35, time_3, 0.3, time_4)
print(res)


```



