# STAT 517 - Lab 04
### March 9, 2023

# Question 3

```{r}
library(MASS)

data(mcycle)
plot(mcycle)


X <- mcycle$accel
t <- mcycle$times
```

```{r}
kernel_1 <- function(t, lambda) {
    n <- length(t)
    cov_mat <- matrix(0, nrow=n, ncol=n)
    for (i in seq_len(n)) {
        for (j in seq(from=i, to=n)) {
            cov_mat[i, j] <- exp(-lambda * abs(t[i] - t[j]))
            cov_mat[j, i] <- cov_mat[i, j]
        }
    }
    return(cov_mat)
}

kernel_2 <- function(t, lambda) {
    n <- length(t)
    cov_mat <- matrix(0, nrow=n, ncol=n)
    for (i in seq_len(n)) {
        for (j in seq(from=i, to=n)) {
            cov_mat[i, j] <- exp(-lambda * (t[i] - t[j])^2)
            cov_mat[j, i] <- cov_mat[i, j]
        }
    }
    return(cov_mat)
}


cov_fn_1 <- function(t, sigma, lambda, nu, a) {
    I <- diag(length(t))
    cov_mat <- sigma * (nu * kernel_1(t, lambda) + a * I)
    return(cov_mat)
}



cov_fn_2 <- function(t, sigma, lambda, nu, a) {
    I <- diag(length(t))
    cov_mat <- sigma * (nu * kernel_2(t, lambda) + a * I)
    return(cov_mat)
}
```


```{r}
likelihood_1 <- function(params, X, t) {
    sigma <- params[1]
    lambda <- params[2]
    mu <- mean(X)
    
    
    if (sigma <= 0 || lambda <= 0) {
        return(-Inf)
    }
    
    n <- length(t)
    
    # # This line below corresponds to the function in the lab
    # # But the covariance matrix is ill-conditioned and is singular
    # cov_mat <- cov_fn_1(t, sigma, lambda, 1, 0)
    
    # Going to add some regularization
    cov_mat <- cov_fn_1(t, sigma, lambda, 1, 1e-9)
    det_cov <- det(cov_mat)
    
    if (det_cov == 0){
        return(-Inf)
    }
    
    delta <- matrix(X - mu, ncol=1)
    ell <- - t(delta) %*% solve(cov_mat) %*% delta - n * log(det_cov)
    return(ell)
}

params <- c(2, 4)

res1 <- optim(params, likelihood_1, X=X, t=t,
              control=c("fnscale"=-1))
mu_est1 <- mean(X)
sigma_est1 <- res1$par[1]
lambda_est1 <- res1$par[2]
print(res1$par)


x <- seq(-50, 50, by=0.5)
gamma1 <- sigma_est1 * exp(- lambda_est1 * abs(x))

plot(x, gamma1, type="l",
     xlab="x", ylab="gamma")
```


```{r}
likelihood_2 <- function(params, X, t) {
    mu <- mean(X)
    sigma <- params[1]
    lambda <- params[2]
    
    if (sigma <= 0 || lambda <= 0) {
        return(-Inf)
    }
    
    n <- length(t)
    cov_mat <- cov_fn_1(t, sigma, lambda, 1/3, 1)
    det_cov <- det(cov_mat)
    
    if (det_cov == 0){
        return(-Inf)
    }
    
    delta <- matrix(X - mu, ncol=1)
    ell <- - t(delta) %*% solve(cov_mat) %*% delta - n * log(det_cov)
    return(ell)
}

params <- c(2, 4)

res2 <- optim(params, likelihood_2, X=X, t=t,
              control=c("fnscale"=-1))
mu_est2 <- mean(X)
sigma_est2 <- res2$par[1]
lambda_est2 <- res2$par[2]
print(res2$par)


x <- seq(-50, 50, by=0.5)
gamma2 <- sigma_est2 * exp(-lambda_est2 * abs(x))

plot(x, gamma2, type="l",
     xlab="x", ylab="gamma")
```


```{r}

likelihood_3 <- function(params, X, t) {
    mu <- mean(X)
    sigma <- params[1]
    lambda <- params[2]
    
    if (sigma <= 0 || lambda <= 0) {
        return(-Inf)
    }
    
    n <- length(t)
    cov_mat <- cov_fn_1(t, sigma, lambda, 10, 1)
    det_cov <- det(cov_mat)
    
    if (det_cov == 0){
        return(-Inf)
    }
    
    delta <- matrix(X - mu, ncol=1)
    ell <- - t(delta) %*% solve(cov_mat) %*% delta - n * log(det_cov)
    return(ell)
}

params <- c(2, 4)

res3 <- optim(params, likelihood_3, X=X, t=t,
              control=c("fnscale"=-1))
mu_est3 <- mean(X)
sigma_est3 <- res3$par[1]
lambda_est3 <- res3$par[2]
print(res3$par)


x <- seq(-50, 50, by=0.5)
gamma3 <- sigma_est3 * exp(-lambda_est3 * abs(x))

plot(x, gamma3, type="l",
     xlab="x", ylab="gamma")
```

```{r}
likelihood_4 <- function(params, X, t) {
    mu <- mean(X)
    sigma <- params[1]
    lambda <- params[2]
    
    if (sigma <= 0 || lambda <= 0) {
        return(-Inf)
    }
    
    n <- length(t)
    
    # # This line below corresponds to the function in the lab
    # # But the covariance matrix is ill-conditioned and is singular
    # cov_mat <- cov_fn_2(t, sigma, lambda, 1, 0)
    
    # Going to add some regularization
    cov_mat <- cov_fn_2(t, sigma, lambda, 1, 1e-8)
    det_cov <- det(cov_mat)
    
    if (det_cov == 0){
        return(-Inf)
    }
    
    delta <- matrix(X - mu, ncol=1)
    ell <- - t(delta) %*% solve(cov_mat) %*% delta - n * log(det_cov)
    return(ell)
}

params <- c(2, 4)

res4 <- optim(params, likelihood_4, X=X, t=t,
              control=c("fnscale"=-1))
mu_est4 <- mean(X)
sigma_est4 <- res4$par[1]
lambda_est4 <- res4$par[2]
print(res4$par)


x <- seq(-50, 50, by=0.5)
gamma4 <- sigma_est4 * exp(-lambda_est4 * x^2)

plot(x, gamma4, type="l",
     xlab="x", ylab="gamma")
```


```{r}
likelihood_5 <- function(params, X, t) {
    mu <- mean(X)
    sigma <- params[1]
    lambda <- params[2]
    
    if (sigma <= 0 || lambda <= 0) {
        return(-Inf)
    }
    
    n <- length(t)
    cov_mat <- cov_fn_2(t, sigma, lambda, 1/3, 1)
    det_cov <- det(cov_mat)
    
    if (det_cov == 0){
        return(-Inf)
    }
    
    delta <- matrix(X - mu, ncol=1)
    ell <- - t(delta) %*% solve(cov_mat) %*% delta - n * log(det_cov)
    return(ell)
}

params <- c(2, 4)

res5 <- optim(params, likelihood_5, X=X, t=t,
              control=c("fnscale"=-1))
mu_est5 <- mean(X)
sigma_est5 <- res5$par[1]
lambda_est5 <- res5$par[2]
print(res5$par)


x <- seq(-50, 50, by=0.5)
gamma5 <- sigma_est5 * exp(-lambda_est5 * x^2)

plot(x, gamma5, type="l",
     xlab="x", ylab="gamma")
```


```{r}
likelihood_6 <- function(params, X, t) {
    mu <- mean(X)
    sigma <- params[1]
    lambda <- params[2]
    
    if (sigma <= 0 || lambda <= 0) {
        return(-Inf)
    }
    
    n <- length(t)
    cov_mat <- cov_fn_2(t, sigma, lambda, 10, 1)
    det_cov <- det(cov_mat)
    
    if (det_cov == 0){
        return(-Inf)
    }
    
    delta <- matrix(X - mu, ncol=1)
    ell <- - t(delta) %*% solve(cov_mat) %*% delta - n * log(det_cov)
    return(ell)
}

params <- c(2, 4)

res6 <- optim(params, likelihood_6, X=X, t=t,
              control=c("fnscale"=-1))
mu_est6 <- mean(X)
sigma_est6 <- res6$par[1]
lambda_est6 <- res6$par[2]
print(res6$par)


x <- seq(-50, 50, by=0.5)
gamma6 <- sigma_est6 * exp(-lambda_est6 * x^2)

plot(x, gamma6, type="l",
     xlab="x", ylab="gamma")
```

